#!/bin/bash

declare -a files=(
  '.bash_profile'
  '.bashrc'
  '.zshrc'
  '.gitconfig'
  '.gitignore_global'
  '.spacemacs'
)

for i in "${files[@]}"
do
   echo $i
   rm ~/$i
   ln -s `pwd`/$i ~/$i
done




